import { StyleSheet } from "react-native";
import {FONT_SIZE_20,FONT_SIZE_18, FONT_SIZE_17, FONT_SIZE_16, FONT_SIZE_15, FONT_SIZE_14, FONT_SIZE_13, FONT_SIZE_12, FONT_SIZE_11} from './FontSizes';
import CustomThemes from "./CustomThemes";
import { color } from "../Constants/Color";

export const CommonTextStyles = StyleSheet.create({ 
  f_sb_fs10_c_black:{
    fontFamily:CustomThemes.fonts.segoebold,
    color:color.black,
    fontSize:FONT_SIZE_18
  },
  f_sr_fs10_c_gray42:{
    fontFamily:CustomThemes.fonts.segoeregular,
    fontSize:FONT_SIZE_15,
    color:color.gray42
  },
  f_sr_fs13_c_blue:{
    fontFamily:CustomThemes.fonts.segoeregular,
    fontSize:FONT_SIZE_13,
    color:color.blue
  },
  f_sb_fs18_c_white:{
    fontFamily:CustomThemes.fonts.segoebold,
    fontSize:FONT_SIZE_18,
    color:color.white
  },
  f_sr_fs16_c_black:{
    fontFamily:CustomThemes.fonts.segoeregular,
    fontSize:FONT_SIZE_16,
    color:color.black
  },
  f_sr_fs16_c_blue:{
    fontFamily:CustomThemes.fonts.segoeregular,
    fontSize:FONT_SIZE_16,
    color:color.blue
  },
  f_sb_fs20_c_black:{
    fontFamily:CustomThemes.fonts.segoebold,
    fontSize:FONT_SIZE_20,
    color:color.black
  },
  f_sr_fs14_c_black:{
    fontFamily:CustomThemes.fonts.segoeregular,
    fontSize:FONT_SIZE_14,
    color:color.black
  },
  f_sr_fs14_c_white:{
    fontFamily:CustomThemes.fonts.segoeregular,
    fontSize:FONT_SIZE_14,
    color:color.white
  },
  f_sr_fs11_c_black:{
    fontFamily:CustomThemes.fonts.segoeregular,
    fontSize:FONT_SIZE_11,
    color:color.black
  },
  f_sb_fs17_c_black:{
    fontFamily:CustomThemes.fonts.segoebold,
    fontSize:FONT_SIZE_17,
    color:color.black
  },
  f_sb_fs16_c_blue:{
    fontFamily:CustomThemes.fonts.segoebold,
    fontSize:FONT_SIZE_16,
    color:color.blue
  },
  f_sr_fs12_c_black:{
    fontFamily:CustomThemes.fonts.segoeregular,
    fontSize:FONT_SIZE_12,
    color:color.black
  },
  f_sr_fs12_c_grey:{
    fontFamily:CustomThemes.fonts.segoeregular,
    fontSize:FONT_SIZE_12,
    color:'#666'
  },
   f_sb_fs12_c_black:{
    fontFamily:CustomThemes.fonts.segoebold,
    color:color.black,
    fontSize:FONT_SIZE_12
  },
  f_sb_fs15_c_yellow:{
    fontFamily:CustomThemes.fonts.segoeregular,
    color:color.yellow,
    fontSize:FONT_SIZE_15
  },
  f_sb_fs15_c_white:{
    fontFamily:CustomThemes.fonts.segoeregular,
    color:color.white,
    fontSize:FONT_SIZE_15
  },
  f_sb_fs20_c_white:{
    fontFamily:CustomThemes.fonts.segoebold,
    color:color.white,
    fontSize:FONT_SIZE_20
  },
  f_sr_fs14_c_grey:{
    fontFamily:CustomThemes.fonts.segoeregular,
    color:'#ccc',
    fontSize:FONT_SIZE_14
  },
  f_sb_fs14_c_black:{
    fontFamily:CustomThemes.fonts.segoebold,
    color:color.black,
    fontSize:FONT_SIZE_14
  },
  f_sb_fs13_c_white:{
    fontFamily:CustomThemes.fonts.segoebold,
    color:color.white,
    fontSize:FONT_SIZE_13
  },
  f_sb_fs14_c_white:{
    fontFamily:CustomThemes.fonts.segoebold,
    color:color.white,
    fontSize:FONT_SIZE_14
  },
   f_sr_fs14_c_yellow:{
    fontFamily:CustomThemes.fonts.segoeregular,
    color:color.yellow,
    fontSize:FONT_SIZE_14,
    textDecorationLine: 'underline',
  },


})